                                                                                                                                                                                                                                                                                                                                   ?column?                                                                                                                                                                                                                                                                                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 INSERT INTO users VALUES ('kdswmuqcgfrn7ck7mjrpkzz43h',1754018157797,1754018157797,0,'calls','',NULL,'','calls@localhost',false,'','Calls','','system_user',false,'{}','{"push": "mention", "email": "true", "channel": "true", "desktop": "mention", "comments": "never", "first_name": "false", "push_status": "away", "mention_keys": "", "push_threads": "all", "desktop_sound": "true", "email_threads": "all", "desktop_threads": "all"}',1754018157797,0,0,'en',false,'','','{"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"}',NULL,0);
 INSERT INTO users VALUES ('nsj8sx75bffgppmicuqiormysr',1754019000006,1754019000006,0,'system-bot','',NULL,'','system-bot@localhost',false,'','System','','system_user',false,'{}','{"push": "mention", "email": "true", "channel": "true", "desktop": "mention", "comments": "never", "first_name": "false", "push_status": "away", "mention_keys": "", "push_threads": "all", "desktop_sound": "true", "email_threads": "all", "desktop_threads": "all"}',1754019000006,0,0,'en',false,'','','{"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"}',NULL,0);
 INSERT INTO users VALUES ('c9ygnoinhpn9tmnhi5u1h8x8sw',1754021556313,1754021556313,0,'boards','',NULL,'','boards@localhost',false,'','Boards','','system_user',false,'{}','{"push": "mention", "email": "true", "channel": "true", "desktop": "mention", "comments": "never", "first_name": "false", "push_status": "away", "mention_keys": "", "push_threads": "all", "desktop_sound": "true", "email_threads": "all", "desktop_threads": "all"}',1754021556313,0,0,'en',false,'','','{"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"}',NULL,0);
 INSERT INTO users VALUES ('ix987f9aejnpfbhihuwqwurzxe',1754018158638,1754117414973,0,'playbooks','',NULL,'','playbooks@localhost',false,'','Playbooks','','system_user',false,'{}','{"push": "mention", "email": "true", "channel": "true", "desktop": "mention", "comments": "never", "first_name": "false", "push_status": "away", "mention_keys": "", "push_threads": "all", "desktop_sound": "true", "email_threads": "all", "desktop_threads": "all"}',1754018158638,1754018158689,0,'en',false,'','','{"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"}',NULL,0);
 INSERT INTO users VALUES ('aym4koxgkpdnbfuz9m6f69ghtc',1754018888445,1754117829961,0,'baophan','$2a$10$KTLuOaZSPO0DzyCbPFjoN.675DEp7kSD3wTCuAy9ibUoiOyglKBc.',NULL,'','baopqt@limgrow.com',false,'','','','system_admin system_user',false,'{}','{"push": "mention", "email": "true", "channel": "true", "desktop": "mention", "comments": "never", "first_name": "false", "push_status": "away", "mention_keys": "", "push_threads": "all", "desktop_sound": "true", "email_threads": "all", "desktop_threads": "all"}',1754018888445,0,0,'en',false,'','','{"manualTimezone": "", "automaticTimezone": "Asia/Saigon", "useAutomaticTimezone": "true"}',NULL,1754117593385);
 INSERT INTO users VALUES ('test123',1754291001537,1754291001537,NULL,'testuser','hashed_password',NULL,NULL,'test@example.com',NULL,'TestNick','UpdatedName','User',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Developer',NULL,NULL,0);
 INSERT INTO users VALUES ('51oa8mbtajyop88wawkzmx9wjh',1754018156927,1754018157049,0,'feedbackbot','',NULL,'','feedbackbot@localhost',false,'','TestCDC','','system_user',false,'{}','{"push": "mention", "email": "true", "channel": "true", "desktop": "mention", "comments": "never", "first_name": "false", "push_status": "away", "mention_keys": "", "push_threads": "all", "desktop_sound": "true", "email_threads": "all", "desktop_threads": "all"}',1754018156927,1754018157049,0,'en',false,'','','{"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"}',NULL,0);
(7 rows)

